spring:
  application:
    name: geteway-service-zuul

#这里的配置表示，访问/it/** 直接重定向到http://www.ityouknow.com/**
zuul:
  routes:
    baidu:
      path: /hello/**
      url: http://localhost:9001/hello/zhangsan
