spring:
  application:
    name: geteway-service-zuul

#这里的配置表示，访问/hello/** 直接重定向到http://localhost:9001/hello/zhangsan
zuul:
  routes:
    baidu:
      path: /hello/**
      url: http://localhost:9001/hello/zhangsan
